<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>PLC_COM</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="src\PlcWpf.Services\" />
    <Folder Include="src\PlcWpf.Comms\" />
    <Folder Include="src\PlcWpf.Core\" />
    <Folder Include="src\PlcWpf.App\" />
  </ItemGroup>

</Project>
